### ISSUE TITLE
Support specifying `jreleaser.yaml` location

### ISSUE THREAD

**Issue by gastaldi** [jreleaser/release-action#17]
It would be nice if we could specify a URL for the `jreleaser.yaml`. My use case is that I need to verify if a project is ready to be deployed to central in projects that do not use JReleaser, so I'd like to run `jreleaser deploy --dry-run` when a PR is opened using a `jreleaser.yml` (or another file name) defined in a separate repository (`OWNER/.github` for example)

**Comment by aalmiray** [comment]
Have you tried passing an explicit `--config-file` flag as argument?

**Comment by gastaldi** [comment]
Ah, that works, thank you!
