### ISSUE TITLE
setup-java input of false is ignored

### ISSUE THREAD

**Issue by dmurat** [jreleaser/release-action#7]
I'm trying to use non-default Java runtime with `release-action`, but without success.
I tried to configure `setup-java` with both `false` and `"false"`, but `release-action` always uses the default Zulu 17 runtime.

I might be wrong, but it looks like the problem is in `action.yml` at line 35:
```
if: ${{ inputs.setup-java }} == 'true' || ${{ inputs.setup-java }} == true
```
I believe that the second condition will be truthy if anything non-empty is configured for `setup-java`

**Comment by aalmiray** [comment]
Release `2.1.2` has the fix, as well as `v2` branch.
